name: Client Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:

defaults:
  run:
    working-directory: client

jobs:
  ci:
    name: Lint and Test Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Cache node modules
        id: cached-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-client-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Check the linting
        run: npm run lint

      - name: Run the tests
        run: npm run test

      - name: Build
        run: npm run build
